# 「PostgreSQL と PgAdmin4 を Docker Compose で立ち上げる」を参考に
# https://zenn.dev/onozaty/articles/postgresql-pgadmin-container
# 公式 は
# https://www.pgadmin.org/docs/pgadmin4/latest/container_deployment.html

version: '3.9'

services:
  db:
    # 日本語化するためDockerfile使用
    build: .
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: flywayTest
    volumes:
      - db-data:/var/lib/postgresql/data

  pgadmin4:
    image: 'dpage/pgadmin4'
    ports:
      - "8000:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      # pgadmin起動時にサーバー接続設定をservers.jsonにて行う
      - ./config/servers.json/testDB.json:/pgadmin4/servers.json
    environment:
      PGADMIN_DEFAULT_EMAIL: user@example.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    depends_on:
      - db

volumes:
  db-data:
  pgadmin-data: